# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170927_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow_set',
            field=models.ManyToManyField(blank=True, through='accounts.Relation', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to='accounts.Profile'),
        ),
    ]
