# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 05:43
from __future__ import unicode_literals

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171005_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=accounts.models.user_path),
        ),
    ]
