# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 08:57
from __future__ import unicode_literals

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='accounts/default/default.jpg', upload_to=accounts.models.user_path),
        ),
    ]
