# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171018_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('선택 안 함', '선택 안 함'), ('여성', '여성'), ('남성', '남성')], default='N', max_length=10),
        ),
    ]
